In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt

In [2]:
import os
print(os.listdir("../dataset/"))

['sample_submission.csv', 'test_images.npy', 'train_images.npy', 'train_labels.csv']


In [ ]:
#Load images with numpy
images = np.load('../dataset/train_images.npy', encoding='bytes')
images.shape

test_images = np.load('../dataset/test_images.npy', encoding='bytes')
images.shape

In [ ]:
#Reshaping image to 100x100
image1 = (images[2][1]).reshape(100,100)
plt.imshow(image1)

In [ ]:
Y_train = pd.read_csv('../dataset/train_labels.csv');

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import seaborn as sns
%matplotlib inline

np.random.seed(2)

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import itertools

from keras.utils.np_utils import to_categorical # convert to one-hot-encoding
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPool2D
from keras.optimizers import RMSprop
from keras.preprocessing.image import ImageDataGenerator
from keras.callbacks import ReduceLROnPlateau

Using TensorFlow backend.


In [7]:
X_train = images[:, 1]
X_test = test_images[:, 1]

In [8]:
# Normalize
X_train = X_train / 255.0
X_test = X_test / 255.0

In [15]:

for a in X_train:
    a.reshape(100, 100)
for a in X_test:
    a.reshape(100, 100)

In [9]:
X_train

array([array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.]), ...,
       array([0., 0., 0., ..., 0., 0., 0.]),
       array([1., 1., 1., ..., 0., 0., 0.]),
       array([0., 0., 0., ..., 0., 0., 0.])], dtype=object)

In [9]:
X_train = X_train.reshape(100, 100)
X_test = X_test.reshape(100, 100)

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [10]:
Y_train = Y_train.iloc[:, 1]


In [11]:
# Dummies one hot
Y_train = pd.get_dummies(Y_train)

In [12]:
Y_train = to_categorical(Y_train, num_classes = 10)

In [13]:
random_seed = 2

In [14]:
X_train, X_val, Y_train, Y_val = train_test_split(X_train, Y_train, test_size = 0.1, random_state=random_seed)


ValueError: Found input variables with inconsistent numbers of samples: [100, 10000]

In [17]:
X_train.shape

(100, 100)